'use client';

import { formatDate } from '@/lib/utils';

// Dynamic import jsPDF since it's client-only
async function getJsPDF() {
  const { jsPDF } = await import('jspdf');
  const autoTable = (await import('jspdf-autotable')).default;
  return { jsPDF, autoTable };
}

type PortfolioItem = {
  title: string;
  category: string;
  status: string;
  current_count: number;
  target_count: number;
  notes: string;
  date_completed: string | null;
  metadata: any;
};

type CaseEntry = {
  title: string;
  date_seen: string;
  specialty_tags: string[];
  presenting_complaint: string;
  key_findings: string;
  diagnosis: string;
  management: string;
  outcome: string;
  learning_points: string;
  reflection: string;
  complexity: string | null;
};

export async function exportPortfolioPDF(
  profileName: string,
  trainingStage: string,
  specialty: string,
  trainingYear: string,
  items: PortfolioItem[]
) {
  const { jsPDF } = await getJsPDF();
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('MedFolio Portfolio Report', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  doc.text(
    'This is an unofficial portfolio summary generated by MedFolio. Always verify requirements with your Deanery.',
    margin,
    y
  );
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Profile info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`${profileName}`, margin, y);
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${specialty} — ${trainingYear} | ${trainingStage}`, margin, y);
  y += 4;
  doc.text(`Generated: ${formatDate(new Date())}`, margin, y);
  y += 10;

  // Summary stats
  const total = items.length;
  const completed = items.filter((i) => i.status === 'completed').length;
  const inProgress = items.filter((i) => i.status === 'in_progress').length;
  const notStarted = items.filter((i) => i.status === 'not_started').length;

  doc.setFillColor(240, 240, 240);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 18, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Overall: ${completed}/${total} complete`, margin + 5, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `${completed} completed · ${inProgress} in progress · ${notStarted} not started`,
    margin + 5,
    y + 13
  );
  y += 25;

  // Group items by category
  const categories: Record<string, PortfolioItem[]> = {};
  items.forEach((item) => {
    if (!categories[item.category]) categories[item.category] = [];
    categories[item.category].push(item);
  });

  // Items table per category
  for (const [category, catItems] of Object.entries(categories)) {
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(category, margin, y);
    y += 2;

    const catCompleted = catItems.filter((i) => i.status === 'completed').length;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text(`${catCompleted}/${catItems.length} complete`, margin, y + 4);
    doc.setTextColor(0, 0, 0);
    y += 6;

    const tableData = catItems.map((item) => [
      item.title,
      `${item.current_count}/${item.target_count}`,
      item.status === 'completed' ? '✓ Done' : item.status === 'in_progress' ? '◐ In Progress' : '○ Not Started',
      item.date_completed ? formatDate(item.date_completed) : '—',
      item.notes ? item.notes.substring(0, 60) + (item.notes.length > 60 ? '...' : '') : '—',
    ]);

    (doc as any).autoTable({
      startY: y,
      head: [['Item', 'Progress', 'Status', 'Date', 'Notes']],
      body: tableData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [6, 196, 177], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 20, halign: 'center' },
        2: { cellWidth: 25 },
        3: { cellWidth: 22 },
        4: { cellWidth: 'auto' },
      },
      didDrawPage: () => {
        // Footer on each page
        doc.setFontSize(7);
        doc.setTextColor(160, 160, 160);
        doc.text(
          'Generated by MedFolio (medfolio.uk) — Not an official NHS document',
          margin,
          doc.internal.pageSize.getHeight() - 10
        );
        doc.setTextColor(0, 0, 0);
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  doc.save(`MedFolio_${specialty}_${trainingYear}_${new Date().toISOString().split('T')[0]}.pdf`);
}

export async function exportCasesPDF(
  profileName: string,
  cases: CaseEntry[]
) {
  const { jsPDF } = await getJsPDF();
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('MedFolio Case Journal', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  doc.text(`${profileName} · Generated: ${formatDate(new Date())}`, margin, y);
  doc.setTextColor(0, 0, 0);
  y += 4;
  doc.text(
    'All cases are anonymised. This is not an official NHS document.',
    margin,
    y
  );
  y += 10;

  // Summary
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(margin, y, contentWidth, 12, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`${cases.length} cases logged`, margin + 5, y + 8);
  y += 18;

  // Each case
  for (let i = 0; i < cases.length; i++) {
    const c = cases[i];

    // Check if we need a new page (estimate case height)
    if (y > 230) {
      doc.addPage();
      y = margin;
    }

    // Case header
    doc.setFillColor(6, 196, 177);
    doc.roundedRect(margin, y, contentWidth, 1, 0, 0, 'F');
    y += 4;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}. ${c.title}`, margin, y + 4);
    y += 6;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    const metaLine = [
      formatDate(c.date_seen),
      c.specialty_tags?.join(', '),
      c.complexity ? `Complexity: ${c.complexity}` : '',
    ]
      .filter(Boolean)
      .join(' · ');
    doc.text(metaLine, margin, y + 4);
    doc.setTextColor(0, 0, 0);
    y += 8;

    // Case fields
    const fields = [
      { label: 'Presenting Complaint', value: c.presenting_complaint },
      { label: 'Key Findings', value: c.key_findings },
      { label: 'Diagnosis', value: c.diagnosis },
      { label: 'Management', value: c.management },
      { label: 'Outcome', value: c.outcome },
      { label: 'Learning Points', value: c.learning_points },
      { label: 'Reflection', value: c.reflection },
    ].filter((f) => f.value);

    for (const field of fields) {
      if (y > 265) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text(field.label.toUpperCase(), margin, y + 3);
      doc.setTextColor(0, 0, 0);
      y += 5;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(field.value, contentWidth);
      doc.text(lines, margin, y + 3);
      y += lines.length * 4 + 4;
    }

    y += 6;
  }

  // Footer on last page
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text(
    'Generated by MedFolio (medfolio.uk) — Not an official NHS document',
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  doc.save(`MedFolio_Cases_${new Date().toISOString().split('T')[0]}.pdf`);
}

export async function exportSingleCasePDF(
  profileName: string,
  c: CaseEntry
) {
  const { jsPDF } = await getJsPDF();
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(c.title, margin, y, { maxWidth: contentWidth });
  const titleLines = doc.splitTextToSize(c.title, contentWidth);
  y += titleLines.length * 7 + 4;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  const meta = [
    formatDate(c.date_seen),
    c.specialty_tags?.join(', '),
    c.complexity ? `Complexity: ${c.complexity}` : '',
    `Author: ${profileName}`,
  ]
    .filter(Boolean)
    .join(' · ');
  doc.text(meta, margin, y);
  doc.setTextColor(0, 0, 0);
  y += 8;

  // Divider
  doc.setDrawColor(6, 196, 177);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Fields
  const fields = [
    { label: 'Presenting Complaint', value: c.presenting_complaint },
    { label: 'Key Findings', value: c.key_findings },
    { label: 'Diagnosis', value: c.diagnosis },
    { label: 'Management', value: c.management },
    { label: 'Outcome', value: c.outcome },
    { label: 'Learning Points', value: c.learning_points },
    { label: 'Reflection', value: c.reflection },
  ].filter((f) => f.value);

  for (const field of fields) {
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text(field.label.toUpperCase(), margin, y);
    doc.setTextColor(0, 0, 0);
    y += 5;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(field.value, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text(
    `Generated by MedFolio (medfolio.uk) · ${formatDate(new Date())} · Not an official NHS document`,
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  const safeName = c.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40);
  doc.save(`MedFolio_Case_${safeName}.pdf`);
}
